### ISSUE TITLE
TangoBox RC9a review

### ISSUE THREAD

**Issue by andygotz** [3Controls/tangobox#63]
Just to say I have tried RC9a and found it much better than RC9 - thanks! 

I tried most of the icons and they worked. The host name is changed and it seems like only the basic servers are started - this is better. Is the WebApp web applications installed? I haven't tried it yet.

Thanks a lot for your efforts and continuous improvements. Tomorrow I would like to send the link around 
for RC10 (or RC9a in case RC10 is not ready).

Cheers

**Comment by andygotz** [comment]
I tried this url http://tangobox-web:8080/TangoWebapp but there does not seem to be anything there.

**Comment by andygotz** [comment]
Problem fixed! There was a /tomcat-users missing at the end of the tomcat-users.xml file. Now TangoWebapp is working again.

**Comment by andygotz** [comment]
This is version 0.1 of TangoWebapp. I am going to upgrade it to 0.2

**Comment by piogor** [comment]
@Patfra, see @andygotz comments on solving problem with TangoWebApp on the `tango-box` container. It may help you with #58  
> I tried this url http://tangobox-web:8080/TangoWebapp but there does not seem to be anything there.
> Problem fixed! There was a /tomcat-users missing at the end of the tomcat-users.xml file. Now TangoWebapp is working again.

**Comment by sergirubio** [comment]
Just a comment, I committed a patch for panic/develop; could you try if it solves the high cpu issues with PyAlarm?

**Comment by sergirubio** [comment]
I also debugged the problem with Vacca, it failed because PyTangoArchiving wasn't installed. 

I have pushed a patch to vacca/develop to reduce the number of panels in elinac demo (and added elinac-full in case all panels are wanted).

But, anyway, PyTangoArchiving should be added to the image.

**Comment by sergirubio** [comment]
Another comment, in the RC9 image I noticed SnapExtractor using 70% of CPU. Did you experience that also?

**Comment by Patfra** [comment]
@andygotz, you just add  /tomcat-users at the end of tomcat-users.xml, reload page http://tangobox-web:8080/TangoWebapp and that fixed the problem?

**Comment by andygotz** [comment]
@sergirubio thanks for the patches. I hope I get time to try them.

@Ingvord where can I specify the TANGO_HOST for the TangoRestServer war? I have set TANGOHOST=tangobox-vm:10000 in /etc/tangorc but it does not use this. It is finding localhost and failing with this error:

INFO: Deploying web application archive /var/lib/tomcat8/webapps/tango.war
Oct 05, 2017 11:38:03 AM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs w$
11:38:03,765 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
11:38:03,765 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:38:03,765 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/var/lib/tomcat8/webapps/tango/WEB-INF/classes/logback$
11:38:03,813 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
11:38:03,817 |-INFO in ch.qos.logback.classic.joran.action.JMXConfiguratorAction - begin
11:38:03,832 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:38:03,838 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
11:38:03,934 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
11:38:03,934 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
11:38:03,934 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
11:38:03,934 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.sift.SiftingAppender]
11:38:03,937 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SIFT]
11:38:03,953 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.sift.MDCBasedDiscriminator] for [di$
11:38:03,967 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
11:38:03,969 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC]
11:38:03,969 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SIFT] to ch.qos.logback.classic.AsyncAppender[ASYNC]
11:38:03,969 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC] - Attaching appender named [SIFT] to AsyncAppender.
11:38:03,969 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC] - Setting discardingThreshold to 51
11:38:03,970 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache] to ERROR
11:38:03,970 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.jacorb] to ERROR
11:38:03,970 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.tango] to ERROR
11:38:03,970 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.tango.rest] to DEBUG
11:38:03,970 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.tango.web] to DEBUG
11:38:03,970 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.quartz] to ERROR
11:38:03,970 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.sf.ehcache] to ERROR
11:38:03,970 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:38:03,970 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
11:38:03,970 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC] to Logger[ROOT]
11:38:03,970 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:38:03,971 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6205361b - Registering current configuration as safe fallback point

WARN 2017-10-05 11:38:04,190 [localhost-startStop-1 -  - o.j.r.s.ResteasyProviderFactory] o.jboss.resteasy.resteasy_jaxrs.i18n.registerProvider:1322 - RESTEASY0021$
INFO 2017-10-05 11:38:04,209 [localhost-startStop-1 -  - o.t.w.s.Launcher] org.tango.web.server.Launcher.contextInitialized:30 - TANGO_HOST=localhost:10000
INFO 2017-10-05 11:38:04,209 [localhost-startStop-1 -  - o.t.w.s.Launcher] org.tango.web.server.Launcher.contextInitialized:34 - TANGO_INSTANCE=development
exception message is: IDL:Tango/DevFailed:1.0
Error Level 0:
         - desc: Connection to database failed  !
org.omg.CORBA.TRANSIENT: Retries exceeded, couldn't reconnect to 127.0.0.1:2809  vmcid: 0x0  minor code: 0  completed: No
         - origin: connect_to_dbase(localhost,10000)
         - reason: TangoApi_DATABASE_CONNECTION_FAILED
         - severity: PANIC

Oct 05, 2017 11:38:04 AM org.apache.catalina.core.StandardContext startInternal

**Comment by andygotz** [comment]
@Ingvord I managed to set the TANGO_HOST but I still have this error (see below). Any idea what is wrong?

WARN 2017-10-05 11:52:15,801 [localhost-startStop-1 -  - o.j.r.s.ResteasyProviderFactory] o.jboss.resteasy.resteasy_jaxrs.i18n.registerProvider:1322 - RESTEASY0021$
INFO 2017-10-05 11:52:15,822 [localhost-startStop-1 -  - o.t.w.s.Launcher] org.tango.web.server.Launcher.contextInitialized:30 - TANGO_HOST=tangobox-vm:10000
INFO 2017-10-05 11:52:15,822 [localhost-startStop-1 -  - o.t.w.s.Launcher] org.tango.web.server.Launcher.contextInitialized:34 - TANGO_INSTANCE=development
exception message is: IDL:Tango/DevFailed:1.0
Error Level 0:
         - desc: device dserver/tangorestserver/development not defined in the database   TangoBox-VM:10000 !
         - origin: DataBase::ImportDevice()
         - reason: DB_DeviceNotDefined
         - severity: ERROR

Error Level 1:
         - desc: Cannot execute command DbImportDevice on sys/database/2
         - origin: Connection.command_inout()
         - reason: TangoApi_CANNOT_EXECUTE_COMMAND
         - severity: PANIC

Oct 05, 2017 11:52:16 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Oct 05, 2017 11:52:16 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/tango] startup failed due to previous errors
INFO 2017-10-05 11:52:16,306 [localhost-startStop-1 -  - o.t.w.s.Launcher] org.tango.web.server.Launcher.contextDestroyed:85 - TangoRestServer has been destroyed!
Oct 05, 2017 11:52:16 AM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesThreads

**Comment by Ingvord** [comment]
@andygotz if you are running server within tomcat check that /var/lib/tomcat8/webapps/tango/WEB-INF/web.xml has correct value for Tango instance i.e.:

```xml
    <context-param>
        <param-name>tango.rest.server.instance</param-name>
        <!-- must be what ever is defined in the DB e.g. sys-->
        <param-value>development</param-value>
    </context-param>
```

Also make sure you are using the latest .zip distribution: [download](https://bitbucket.org/hzgwpn/mtangorest.server/downloads/mtangorest.server-rc4-2.2.zip)

BTW how did you manage to set TANGO_HOST?

**Comment by andygotz** [comment]
OK now I worked it out (after a reboot). @Patfra you need to add the missing tomcat-users at the end of the xml file AND copy the tango.war to webapp AND rename the TangoRestServer instance to development (or rename it in web.xml as explained by @Ingvord  above).

**Comment by piogor** [comment]
The RC10 is released and points mentioned here are addressed. Closing the issue.
